days = 0
while days < 12:
    days += 1
    if days == 1:
        print("On the first day of christmas \nA partridge in a pear tree")
        print()

    elif days == 2:
        print("On the second day of christmas \nTwo turtle doves")
        print("A partridge in a pear tree")
        print()

    elif days == 3:
        print("On the third day of christmas \nThree french hens")
        print("Two turtle doves")
        print("A partridge in a pear tree")
        print()

    elif days == 4:
        print("On the fourth day of christmas \nFour calling birds")
        print("Three french hens")
        print("Two turtle doves")
        print("A partridge in a pear tree")
        print()
    elif days == 5:
        print("On the fifth day of christmas \nFive golden rings")
        print("Four calling birds")
        print("Three french hens")
        print("Two turtle doves")
        print("A partridge in a pear tree")
        print()
    elif days == 6:
        print("On the sixth day of christmas \nSix geese a laying")
        print("Five golden rings")
        print("Four calling birds")
        print("Three french hens")
        print("Two turtle doves")
        print("A partridge in a pear tree")
        print()
    elif days == 7:
        print("On the seventh day of christmas \nSeven swans a swimming")
        print("Six geese a laying")
        print("Five golden rings")
        print("Four calling birds")
        print("Three french hens")
        print("Two turtle doves")
        print("A partridge in a pear tree")
        print()
    elif days == 8:
        print("On the eighth day of christmas \nEight maids a milking")
        print("Seven swans a swimming")
        print("Six geese a laying")
        print("Five golden rings")
        print("Four calling birds")
        print("Three french hens")
        print("Two turtle doves")
        print("A partridge in a pear tree")
        print()
    elif days == 9:
        print("On the ninth day of christmas \nNine ladies dancing")
        print("Eight maids a milking")
        print("Seven swans a swimming")
        print("Six geese a laying")
        print("Five golden rings")
        print("Four calling birds")
        print("Three french hens")
        print("Two turtle doves")
        print("A partridge in a pear tree")
        print()
    elif days == 10:
        print("On the tenth day of christmas \nTen lords a-leaping")
        print("Nine ladies dancing")
        print("Eight maids a milking")
        print("Seven swans a swimming")
        print("Six geese a laying")
        print("Five golden rings")
        print("Four calling birds")
        print("Three french hens")
        print("Two turtle doves")
        print("A partridge in a pear tree")
        print()
    elif days == 11:
        print("On the eleventh day of Christmas \nEleven pipers piping")
        print("Ten lords a-leaping")
        print("Nine ladies dancing")
        print("Eight maids a milking")
        print("Seven swans a swimming")
        print("Six geese a laying")
        print("Five golden rings")
        print("Four calling birds")
        print("Three french hens")
        print("Two turtle doves")
        print("A partridge in a pear tree")
        print()
    elif days == 12:
        print("On the twelfth day of Christmas")
        print("Eleven pipers piping")
        print("Ten lords a-leaping")
        print("Nine ladies dancing")
        print("Eight maids a milking")
        print("Seven swans a swimming")
        print("Six geese a laying")
        print("Five golden rings")
        print("Four calling birds")
        print("Three french hens")
        print("Two turtle doves")
        print("A partridge in a pear tree")
        print()
        